### PR TITLE
Add Ericsson Summer 25 

### PR DESCRIPTION
**Pull request by b8zhong**
Add a few roles

### CODE REVIEW

**Review by Dannny-Babs — CHANGES_REQUESTED** [review]
Hey, please add the roles to the top. The current list is not in alphabetical order, but is instead based on recent postings.

**Comment by b8zhong** [comment]
Got it!

**Comment by b8zhong** [comment]
Done - @Dannny-Babs

**Review by Dannny-Babs — APPROVED** [review]
Great, thanks for help!

**Pull request merged**
